# Generated by Django 5.1.7 on 2025-08-06 13:39

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(default='nenhum@provedor.com', max_length=254, unique=True)),
                ('oab', models.CharField(default='Nenhuma OAB', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(default='Sem telefone.', max_length=20, unique=True)),
                ('dataNascimento', models.DateField()),
                ('nacionalidade', models.CharField(default='Nenhuma nacionalidade.', max_length=255)),
                ('profissao', models.CharField(default='Sem profissão.', max_length=255)),
                ('parceiro', models.CharField(default='Sem parceiro.', max_length=255)),
                ('inss', models.CharField(default='Nenhuma senha.', max_length=255)),
                ('cep', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('rua', models.CharField(default='Sem rua.', max_length=255)),
                ('numero', models.IntegerField(default=0)),
                ('cidade', models.CharField(default='Sem cidade.', max_length=255)),
                ('estado', models.CharField(default='Sem estado.', max_length=255)),
                ('bairro', models.CharField(default='Sem bairro.', max_length=255)),
                ('observacoes', models.TextField(blank=True, default='Nenhuma observação.')),
                ('foto', models.ImageField(blank=True, default='clientes/default.jpg', null=True, upload_to=main.models.caminho_imagem)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(default='Sem telefone.', max_length=20, unique=True)),
                ('observacao', models.TextField(blank=True, default='Nenhuma observação.')),
                ('IdAdvogado', models.IntegerField(default=0)),
                ('cpf', models.CharField(default='Sem CPF.', max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroProcesso', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('arquivado', 'Arquivado')], default='pendente', max_length=50)),
                ('grupoAcao', models.CharField(default='Sem grupo', max_length=50)),
                ('dataContrato', models.DateTimeField(blank=True, default='2000-01-01 00:00:00')),
                ('classificacao', models.CharField(blank=True, choices=[('ruim', 'Ruim'), ('regular', 'Regular'), ('bom', 'Bom'), ('excelente', 'Excelente')], default='regular', max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('prioritario', models.BooleanField(default=False)),
                ('advogadoCriadorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTarefa', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('dataInicio', models.DateTimeField(auto_now_add=True)),
                ('prazoFinal', models.DateTimeField(blank=True, null=True)),
                ('urgente', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluida'), ('atrasada', 'Atrasada')], max_length=50)),
                ('observacoes', models.TextField(blank=True, default='Nenhuma observação.')),
                ('advogadoCriadorId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='advogadoCriador', to=settings.AUTH_USER_MODEL)),
                ('advogadoResponsavelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advogadoResponsavel', to=settings.AUTH_USER_MODEL)),
                ('processoOrigemId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.processo')),
            ],
        ),
    ]
