# Generated by Django 5.1.7 on 2025-04-12 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=10)),
                ('email', models.EmailField(default='nenhum@provedor.com', max_length=254, unique=True)),
                ('oab', models.CharField(default='Nenhuma OAB', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('sexo', models.CharField(max_length=10)),
                ('nacionalidade', models.CharField(default='Nenhuma nacionalidade.', max_length=255)),
                ('senhaInss', models.CharField(default='Nenhuma senha.', max_length=255)),
                ('fidelizado', models.BooleanField(default=False)),
                ('telefone', models.CharField(default='Sem telefone.', max_length=20)),
                ('parceiro', models.CharField(default='Sem parceiro.', max_length=255)),
                ('profissao', models.CharField(default='Sem profissão.', max_length=255)),
                ('cep', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(default='Sem endereço.', max_length=255)),
                ('observacoes', models.TextField(default='Nenhuma observação.')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('dataCriacao', models.DateTimeField(blank=True, default='2000-01-01 00:00:00')),
                ('dataEncerramento', models.DateTimeField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=50)),
                ('prioritario', models.BooleanField(default=False)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataEncerramento', models.DateTimeField(blank=True, null=True)),
                ('prazo', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('prioritario', models.BooleanField(default=False)),
                ('advogadoCriador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advogadoCriador', to=settings.AUTH_USER_MODEL)),
                ('advogadoResponsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advogadoResponsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
