# Generated by Django 5.1.7 on 2025-04-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='oab',
            field=models.CharField(default='Nenhuma OAB', max_length=20),
        ),
    ]
