# Generated by Django 5.1.7 on 2025-03-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='data_abertura',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='data_fechamento',
        ),
        migrations.AddField(
            model_name='advogado',
            name='email',
            field=models.EmailField(default='nenhum@provedor.com', max_length=254),
        ),
    ]
