# Generated by Django 5.1.7 on 2025-11-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cliente_parceiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='descricao',
            new_name='observacoes',
        ),
        migrations.RemoveField(
            model_name='tarefas',
            name='descricao',
        ),
    ]
