# Generated by Django 5.1.7 on 2025-03-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_processo_data_abertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='senha',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
