# Generated by Django 5.1.7 on 2025-11-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_descricao_processo_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='arquivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='bairro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='estado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='representante',
            name='numero',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='representante',
            name='rua',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
