# Generated by Django 5.1.7 on 2025-03-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advogado_is_active_advogado_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advogado',
            name='senha',
        ),
    ]
