# Generated by Django 5.1.7 on 2025-03-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_advogado_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='email',
            field=models.EmailField(default='nenhum@provedor.com', max_length=254, unique=True),
        ),
    ]
